services:
  postgres:
    image: postgres:latest
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 321
    volumes:
      - /home/acidos/voc/memer.site/postgresData:/var/lib/postgresql/data
  mongodb:
    image: mongo:4
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - /home/acidos/voc/memer.site/MongoDBData:/data/db
    depends_on:
      - postgres
  postgrest:
    image: postgrest/postgrest:latest
    depends_on:
      - postgres
    environment:
      PGRST_DB_URI: postgres://postgres:321@192.168.0.112:5432/demo
      PGRST_DB_SCHEMA: bookings
      PGRST_DB_ANON_ROLE: web_anon
    ports:
      - "3000:3000"
volumes:
  mongodb_data:
