services:
  postgres:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 321
    volumes:
      - /home/acidos/voc/memer.site/postgresData:/var/lib/postgresql/data
  mongodb:
    image: mongo:4
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - /home/acidos/voc/memer.site/MongoDBData:/data/db
    depends_on:
      - postgres
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
    volumes:
      - /home/acidos/voc/memer.site/RabbitMQData:/var/lib/rabbitmq
volumes:
  mongodb_data:
