# global config
global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s
alerting:
  alertmanagers:
  - follow_redirects: true
    enable_http2: true
    scheme: http
    timeout: 10s
    api_version: v2
    static_configs:
    - targets: []
scrape_configs:
  - job_name: 'messagerserver'
    scrape_interval: 10s
    metrics_path: /metrics
    static_configs:
      - targets: ['192.168.0.112:22366']
  - job_name: 'fastapi_server'
    scrape_interval: 10s
    metrics_path: /metrics
    static_configs:
      - targets: ['192.168.0.112:9001']